Update maven and mappings
Legacy-Fabric/fabric-loader-1.8.9 pull request #11
Opened 2021-06-11 13:32 UTC by Grayray75

Uses the new maven and updates yarn mappings.

2021-06-12 01:17 UTC, hYdos requested changes

2021-06-12 01:17 UTC, hYdos commented on build.gradle
> +		name = 'legacy-fabric'
change the ' to " please

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/EntrypointStorage.java
> +import net.fabricmc.loader.EntrypointStorage.Entry;
what happened here

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/discovery/ModResolver.java
> +import net.fabricmc.loader.discovery.ModResolver.UrlProcessAction;
you have left quite a few unused imports in

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/gui/FabricMainWindow.java
> +import net.fabricmc.loader.gui.FabricMainWindow.IconSet;
concern

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/launch/knot/KnotClassDelegate.java
> +import net.fabricmc.loader.launch.knot.KnotClassDelegate.Metadata;
2 more after this

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java
> +import net.fabricmc.loader.metadata.V0ModMetadata.Mixins;
how did this happen

2021-06-12 01:17 UTC, hYdos commented on src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
> +import net.fabricmc.loader.metadata.V1ModMetadata.IconEntry;
I'm concerned

2021-06-12 08:29 UTC, Grayray75 commented
@hYdos All these imports where generated by gradle.
But you are right they are all unnecessary...

2021-06-27 17:18 UTC, BluCobalt commented
Going to run workflow

2021-06-27 17:19 UTC, BluCobalt approved these changes

2021-06-27 17:20 UTC, halotroop2288 approved these changes

2021-06-27 17:46 UTC, BoogieMonster1O1 approved these changes

2021-06-27 17:46 UTC, merged